"""Contains sql requests without variables."""

from .completed_sql import (
    CREATE_EXTENSION_UUID,
    CREATE_SCHEMA_MIGRATIONS,
    CREATE_TABLE_SCHEMAS,
    SELECT_ALL_MIGRATIONS,
    SELECT_COLUMNS_INFO,
    SELECT_SCHEMAS_INFO,
    SELECT_TABLE_INFO,
    TRY_CONNECTION,
)
from .uncompleted_sql import (
    CHECK_DATABASE,
    CREATE_DATABASE,
    DISCONNECT_FROM_DB,
    DROP_DATABASE,
    FIND_MAP,
    FIND_MAX_VERSION,
    FIND_MIGRATION,
    FIND_MIGRATION_VERSION,
    INSERT_NEW_MIGRATION,
    LOAD_MIGRATION,
)

__all__ = [
    "CHECK_DATABASE",
    "CREATE_DATABASE",
    "CREATE_SCHEMA_MIGRATIONS",
    "CREATE_TABLE_SCHEMAS",
    "CREATE_EXTENSION_UUID",
    "SELECT_COLUMNS_INFO",
    "SELECT_SCHEMAS_INFO",
    "SELECT_TABLE_INFO",
    "INSERT_NEW_MIGRATION",
    "FIND_MIGRATION",
    "FIND_MAX_VERSION",
    "FIND_MAP",
    "FIND_MIGRATION_VERSION",
    "DISCONNECT_FROM_DB",
    "DROP_DATABASE",
    "SELECT_ALL_MIGRATIONS",
    "LOAD_MIGRATION",
    "TRY_CONNECTION",
]
