name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_and_tests:
    uses: ./.github/workflows/tests.yml

  publish:
    needs: build_and_tests
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1